### ISSUE TITLE
no ouput

### ISSUE THREAD

**Issue by rob123king** [holtjma/msbwt#2]
gunzip -c reads.sorted.txt.gz | tr NT TN | ropebwt2 -LR | tr NT TN | msbwt convert /path/to/output/msbwt

This command does not produce any output file or folder when I try it. Is the tr NT TN command use twice correct?

**Comment by holtjma** [comment]
Yes, you should use the command twice if you're using ropebwt2.

Did the basic example command work? (i.e. `echo -e "T\$CAA" | msbwt convert ./local_test`)  That should create a small one in a `local_test` directory.

**Comment by rob123king** [comment]
That worked fine. I've produced the command 
gunzip -c reads.sorted.txt.gz | tr NT TN | ropebwt2 -LR | tr NT TN > out.txt
Now trying 
cat out.txt | msbwt convert ./msbwt_test

and this worked, maybe without the ./ I was having problems but seems like worked fine. Thanks

**Comment by holtjma** [comment]
Yea, I've had issues on some systems when a './' or full path isn't present.  Glad you got it worked out!
