### ISSUE TITLE
TypeError: expected bytes, str found

### ISSUE THREAD

**Issue by Parsoa** [holtjma/msbwt#3]
I always get this error when trying to import a MSBWT using the Python API.

I have a small FASTQ file, 400 long sequencing reads. I've tried creating the BWT using both the msbwt package and by converting from the output of ropebwt2. Querying using the command-line also works so I'm wondering what if I'm missing anything. The package has been installed with Python 2.7. 

I can provide the data needed to reproduce the above error if necessary.

**Comment by holtjma** [comment]
Hey, did you figure out the issue you were having?
